### PR TITLE
Convert to a CLI

### PR DESCRIPTION
**Pull request by arnau**
Hi,

I started this branch to fix error handling when Tfl returns an empty `TimeTable`.  For convenience I ended up upgrading dependencies and adding Clap to handle different commands.

In short this PR includes:
- Update dependencies.
- Add CLI handler.
- Add `fetch-lines` command.  Fetches data from Tfl and caches it.  Optionally it can do the transformation to GTFS.
- Add `transform` command.  Transforms the cached data to the given format (just GTFS atm).
- Up to date README.

I know it diverges a from your original program.  Let me know if you prefer me to keep the fork myself.

### CODE REVIEW

**Comment by ghost** [comment]
Super cool you found this little program useful, and fixed some of my hacks to get it done quickly. Will review more thoroughly Monday and merge if I don't see anything too problematic with the way I use it now

**Comment by arnau** [comment]
I did some more polishing and added `--sample <size>`.  Arguably only useful for testing but found it useful.

**Comment by teburd** [comment]
This seems like a really nice set of changes, I'm going to go ahead and merge these in. If you don't mind, after I merge, send me another PR with your name added to the newly added AUTHORS file.

**Comment by arnau** [comment]
Hey, sorry I just spot a silly mistake in `src/tfl/client.rs:125`.  There is a missing comma in it :(

I will do that soon.

**Pull request merged**
